export function normalizeNutritionInsight(raw: any) {
  const diagnosisText = typeof raw?.diagnosis === "string" ? raw.diagnosis : raw?.diagnosis?.summary || raw?.diagnosis?.message || raw?.diagnosis?.meaning || "Nutrition imbalance detected based on recent intake patterns.";

  const recommendationsRaw = raw?.recommendations || raw?.diagnosis?.recommendations || [];

  const recommendations = recommendationsRaw.map((r: any) => ({
    action: r.action || r.recommendation || r.description || r.title || r.message || "Increase nutritional intake",
    impact: r.impact || r.reason || r.rationale || r.explanation || r.prediction || "Supports goal alignment",
  }));

  return {
    diagnosis: diagnosisText,

    confidence: typeof raw?.confidence === "number" ? raw.confidence : 0.75, // SYSTEM DEFAULT, not AI

    root_causes: raw?.root_causes || raw?.diagnosis?.signals_addressed || raw?.diagnosis?.signals_used || [],

    recommendations,

    prediction: {
      risk: raw?.prediction?.risk || raw?.prediction?.message || "Moderate performance degradation",
      timeframe: raw?.prediction?.timeframe || "7–14 days",
    },

    explainability: {
      triggered_signals: raw?.explainability?.triggered_signals || raw?.diagnosis?.signals_addressed || raw?.diagnosis?.signals_used || [],
      reasoning: raw?.explainability?.reasoning || "Insight generated by evaluating recent nutrition patterns against goal thresholds.",
    },

    warning: raw?.warning || undefined,
  };
}
